### ISSUE TITLE
Run postgresql as part of full nodeset

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#121]
Currently it is required to run `postgresql` for each data node as it is part of the node. 

We can start `postgresql` as `pre_start` job, which is fine for single data-node. 
When you have to start multiple data-nodes in the network it's not very practical.

Current workaround is to copy the `pre_start` job multiple times and change port. We should implement proper solution.

### Solution 1.

Add option to start `postgresql` as part of `node_set` in `hcl` config.

### Solution 2.

Implement and provide the example of  `node-set` template

**Comment by gordsport** [comment]
Closing as completed
