### ISSUE TITLE
Implement S3 upload command

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#126]
Nomad can download configurations like:
- genesis
- vega config
- tendermint config
- wallets
- passphrase files 

to the server from sources supported by [hashicorp go-getter](https://github.com/hashicorp/go-getter) library.

We are currently downloading them from the S3 compatible bucket. At the moment we are updating them manually after everything is generated with the following commands: 

```bash
aws s3 rm --recursive s3://vegacapsule-test/stagnet3
aws s3 cp --recursive ./stagnet3/home/ s3://vegacapsule-test/stagnet3/
```

But it would be nice to have a command to sync the local state with the remote one or maybe do it automatically when something is changed in the network??

**Comment by gordsport** [comment]
Closing ahead of the discussion on using VC for our networks. 

If we decide all issues with this label can be reviewwed
