### ISSUE TITLE
Add job for unsafe_reset_all in stagnet3

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#128]
Currently, we have the command unsafe_reset_all which runs on the local nodes, but we can do it with `nomad alloc exec` than it will work with remote network as well

**Comment by gordsport** [comment]
Closing ahead of discussing the stagnet 3 / capsule for our networks use

**Comment by gordsport** [comment]
@daniel1302 
We have to discuss the future for stagnet3 / vega networks - Ive closed this ahead of us discussing.

Please can you let me know the priority of this / if we should re-open now?
