### ISSUE TITLE
Set up TLS for Stagnet 3 so we have HTTPS

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vegacapsule#152]
This is to set up TLS for `tm.nXX.stagnet3.vega.xyz` and `api.nXX.stagnet3.vega.xyz` URLs. `nXX.stagnet3.vega.xyz` already has it.

In practice we need to review the caddyfile config, and re-do it by separating:
- vega core stays under `nXX.stagnet3.vega.xyz` (and only vega core)
- data-node goes under `api.nXX.stagnet3.vega.xyz`
  - also GraphQL goes under the standard path
  - for validators, when the data-node is not running, can we somehow detect that situation and handle accordingly (so we don't have to keep separate config for validator and non-validator)
- tendermint goes under `tm.nXX.stagnet3.vega.xyz`

**Comment by fkondej** [comment]
We need to update caddy config: https://github.com/vegaprotocol/networks-internal/blob/main/stagnet3/vegacapsule/jobs/node_set.tmpl.nomad#L91-L188
