### ISSUE TITLE
Upgrade smart contracts(we need to upgrade to the latest version of smart contracts)

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vegacapsule#159]
Upgrade smart contracts(we need to upgrade to the latest version of smart contracts) (Emil to deploy all the latest contracts required

### Contracts to upgrade

Current Smart Contract addresses (deployed to Ropsten):
- Multisig Control: `0xDD2df0E7583ff2acfed5e49Df4a424129cA9B58F`
  - needs to be upgraded, this is the old version,
- ERC20 Bridge: `0x11E84824Eb84ac2aa54E1336732d534F7A0E1E64`
  - needs to be upgraded, it is a new version, but not the latest,
- Asset Pool: `0x82A557e31c7ac6B8F64704d740abE1f4c6f38Ca9`
- Staking Bridge: `0xA7298dbC0C0Df4739Ca6a5E5440577cC39f37222`
- Vega Token: `0x123CB30f41Af7552561A4b9A6e920DEAA6b58810`

### Deployer account

Please use `0x5D48FB8c2ff286eD885b510b6Ee77990024E7730` for deployment, you can find the private key here: https://vault.ops.vega.xyz/ui/vault/secrets/wallet/show/ethereum/stagnet3/main.

### Signers

There are seven signers in the Multisig: `n01`, `n02`, `n03`, ... `n07`.
You can find the private keys of signers here: https://vault.ops.vega.xyz/ui/vault/secrets/network/list/stagnet3/.

**Note:** Please use `GitHub` + GitHub token (with `read:org` permission) to log in to https://vault.ops.vega.xyz

### Assets to list

Based on [Stagnet 2 genesis](https://github.com/vegaprotocol/ansible/blob/master/roles/vegaserver/files/home/vega/genesis-app-state.json-stagnet2.vega.xyz#L111-L230):
- [x] tBTC TEST - `0xC912F059b4eCCEF6C969B2E0e2544A1A2581C094`, `5cfa87844724df6069b94e4c8a6f03af21907d7bc251593d08e4251043ee9f7c`
- [x] tDAI TEST - `0x6E3b01547c634942F9073CE863682ab32Dc500fc`, `6d9d35f657589e40ddfb448b7ad4a7463b66efb307527fedd2aa7df1bbd5ea61`
- [x] tEURO TEST - `0xD03f574C22EC71b5834DAE1D4cfBD00AcbAfAb89`, `8b52d4a3a4b0ffe733cddbc2b67be273816cfeb6ca4c8b339bac03ffba08e4e4`
- [x] tUSDC TEST - `0xCc1dE7A9ff1dF05B9f0e49CBfFCA1D02cb5a0E40`, `993ed98f4f770d91a796faab1738551193ba45c62341d20597df70fea6704ede`
- [x] Woz Token (Vega) - `0x5E4b9aDA947130Fc320a144cd22bC1641e5c9d81`, `ce3fb1ab0717f0adbce019d7aef53aacdbadefe2d30ad1647b55f134d4072c90`
- [x] Tim Token (Vega) - `0x920B2375BCAC8cCDfDEFD74426c55C48e0304e4F`, `2282ffc06a557173d297739305cc69f6444cdbbb1089df7d9aef32bbfd735ba1`
- [x] Steve Token (Vega) - `0x5a16941cca2Db4AcdFC28Ac77a3e9652Fdf102e1`, `ba98cdeeec849a053e60cc03808e91e90d9d2e62425c76a590617b95ad41a066`
- [x] Liquidity Reward Token (Vega) - `0xD2f21E37e78dD91b60FE3dD74A112e1a53b33057`, `98032ba34576f8012de9b822e1da3ed4b6223a4f4e05f573002d441ffb4bf314`
- [x] Maker Reward Token (Vega) - `0x8ec701DA58394F5d2c8C2873D31039454D5845C1`, `ebcd94151ae1f0d39a4bde3b21a9c7ae81a80ea4352fb075a92e07608d9c953d`
- [x] Taker Reward Token (Vega) - `0xf700Ce952B6EA11c01b43e5579C6D63286ff8CF0`, `449dbfb66e7a444c485b4fdc77ddc6bbf81abbf7c8e247ac299c25e9557b99cf`

## Acceptance criteria

- [x] New Multisig Control deployed and configured
- [x] New ERC20 Bridge deployed and configured
- [x] Asset Pool configured to point to new smart contracts
- [x] `0x5D48FB8c2ff286eD885b510b6Ee77990024E7730` used as a deployer
- [ ] `n01` ... `n07` are signers in Multisig Control
- [x] threshold set to 667 in Multisig
- [x] ten above assets listed on ERC20 Bridge
- [ ] Vega Token listed on ERC20 Bridge (verify with Jeremy if that is needed)
- [x] New Smart Contract addresses given to the devops team

**Comment by emilbayes** [comment]
New addresses:

Multisig: `0xC6c1C04c82b6a50b50a569F8b6eDD266795A0103`
Bridge: `0xbc511C8dBBf67868f262c2920e8235B54dC22099`

**Comment by emilbayes** [comment]
So by @daniel1302 guidance, it ended up being `n02` ... `n09`

**Comment by emilbayes** [comment]
New addresses are:

```
const multisigAddress = '0x0a432BBc9A7aBC4b7F308013F2E5988C2A8fe653'
const bridgeAddress = '0x5F0Aa66E2E2662bf0DC30c23e776a11B89142B36'
```

**Comment by fkondej** [comment]
Looks good, thank you!!
