### ISSUE TITLE
Remove requirement for GITHUB_TOKEN in `install-bins` option

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vegacapsule#170]
Given https://github.com/vegaprotocol/vega & https://github.com/vegaprotocol/data-node are open source, there should be no need to pass a github token in to this command.

# Tasks
- [ ] Make token optional in the code
- [x] Update the `README.md`

**Comment by gordsport** [comment]
readme started in:
- https://github.com/vegaprotocol/vegacapsule/pull/224

**Comment by gordsport** [comment]
Closing as moved to `done`
