### ISSUE TITLE
Add support for `data-node` in the `vegacapsule nodes unsafe-reset-all`

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#174]
There is a PR pending for the `data-node`: https://github.com/vegaprotocol/data-node/pull/721

After the above PR is merged We should modify the `vegacapsule nodes unsafe-reset-all` command to restart the data node as well as the vega core and tendermint.

Currently, there is a problem that after the network is restarted, a new `chain id` is generated and the `full node` returns an error, that different chain is required.

Command source code: https://github.com/vegaprotocol/vegacapsule/blob/main/cmd/nodes_reset_state.go

**Comment by gordsport** [comment]
This is no longer required
