### ISSUE TITLE
Add support for `relative path` for the`config.OutputDir`

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#175]
Currently, We enforced the `config.OutputDir` to be an absolute path which is perfectly fine for most of the scenarios in local development but when your paths do not match between servers where you want to execute vegacapsule you cannot do anything with your network.

We should add somehow support for the relative path.

**Comment by daniel1302** [comment]
This was a blocker for our stagnet3 pipeline. I have implemented fix here(https://github.com/vegaprotocol/vegacapsule/pull/176) but it is blocked by other pull requests:

- https://github.com/vegaprotocol/vegacapsule/pull/172
- https://github.com/vegaprotocol/vegacapsule/pull/168
- https://github.com/vegaprotocol/vegacapsule/pull/133

**Comment by gordsport** [comment]
Closing as last PR now closed and others merged
