### ISSUE TITLE
Network state not starting cleanly from hard coded param settings

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vegacapsule#182]
There is a problem with VC and network state. Ive updated a few network params during a test which completed ok.
I then restarted the network (nomad clean restart and network all services restarted)
My params are still set to previous settings so I believe the state is still being picked up locally.

**Comment by karlem** [comment]
Well you have to `destroy` and `bootstrap` if you want to start network with new genesis.

**Comment by vega-paul** [comment]
how is it that we are able to change and reset params through system test runs without destroying the network?
only these two are not reset

        "limits.assets.proposeEnabledFrom": "2021-12-17T14:34:26Z",
        "limits.markets.proposeEnabledFrom": "2021-12-17T14:34:26Z"

**Comment by karlem** [comment]
@vega-paul How do you change them in system tests? Is it by modifying genesis or network param proposals?

**Comment by gordsport** [comment]
Closing as there has been flags added that allows a new genesis file to be loaded into the network
