### ISSUE TITLE
Set skip-timeout-commit to true for better block times

### ISSUE THREAD

**Issue by peterbarrow** [vegaprotocol/vegacapsule#194]
With the config option `skip-timeout-commit` set to false, the block will always take at least a second which makes timing different networks difficult. By setting it to true, the blocks can be produced when ready so the timings will show a much better representation of the network latency.

**Comment by ze97286** [comment]
this description is correct only if TimeoutCommit = 1. If it's set to 0, it doesn't matter what skip-timeout-commit is set to.

**Comment by ze97286** [comment]
To be more accurate - it's not even correct with any timeout commit - timeout-commit doesn't mean it adds at least one second (or any number of seconds) - it means how much time to wait after there's already a consensus for the block proposal and commit can go ahead - to give a chance for the last votes to come in. So the change is good, but I would imagine in most cases of running capsule this wait will never take place anyhow.
