### ISSUE TITLE
Readme: Clarify what's in the config file

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vegacapsule#198]
It’s not clear what parameters are available in the configuration(the config.hcl file).

**Comment by gordsport** [comment]
Can we make it more obvious as to what each of the config files give us?

- whoever created the configs, can we get a summary of what these are?
- document these

**Comment by gordsport** [comment]
Closing as a duplicate of: 
- https://github.com/vegaprotocol/vegacapsule/issues/9
