### ISSUE TITLE
Add custom nomad template support for faucet/wallet structures

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#208]
We plan to use pre and post-start jobs for faucet/wallets in the stagnet3. Currently, it is very hacky to deploy them as we have to use a pre-generate structure. 

# TODOs:

- [ ] Add nomad template support to faucet/wallet structures in vegacapsule configuration

**Comment by gordsport** [comment]
Closing ahead of  discussing the stagnet 3 / capsule for our networks use
