### ISSUE TITLE
Check datanode committed block height before shutting it down on protocol upgrade

### ISSUE THREAD

**Issue by ettec** [vegaprotocol/vegacapsule#225]
Vegaconsole (VC) needs to ensure that datanode has processed all blocks that core has processed at the point of upgrade such that it can safely shut down the datanode.  This is to avoid a situation where core upgrades at block X, but datanode is shutdown having only processed block X -1 ( or X -2 etc). were this to happen, when core is restarted from snapshot at block X, datanode (after restart) would be missing blocks and would complain. There would be no easy way out of this situation other than rolling back core to a previous snapshot or getting a dump of datanode with height at X or above.  We want to avoid this.  Short term a pause between shutting down core and datanode of a few seconds to ensure all events are processed would 'probably' suffice, but is riskier.

Corresponding datanode ticket to add an API for this: 

https://github.com/vegaprotocol/vega/issues/5842

**Comment by ze97286** [comment]
a delay is already built into the the killing of the processes isn't it? @karlem

**Comment by karlem** [comment]
A delay is built in already. We run sigterm and they wait. Although a core node would also need to make sure that it send all the events before stopping (which I think it probably does). On the other hand the API call might be even safer the delay.....

**Comment by gordsport** [comment]
Closing as capsule already can handle this
