### ISSUE TITLE
Use the correct published docker containers for the front end config based on the users machine/OS

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vegacapsule#230]
Currently the VegaCapsule `net_confs/config_frontends.hcl` use published docker containers/images that are not compatible with Mac M1 computers. 

Work is to be done in the following issue to publish docker containers/images that support M1 Macs.

- https://github.com/vegaprotocol/frontend-monorepo/issues/1058

We need a way in VegaCapsule to ensure that based on the users machine/OS the correct containers/images are used.

It is expected that early users of VegaCapsule (market makers / people building strategies) will need the front ends and could very well be using M1 macs. Currently these users are unable to do so.

**Comment by gordsport** [comment]
Blocked until the following is completed
- https://github.com/orgs/vegaprotocol/projects/110/views/25

**Comment by mkjmdski** [comment]
current PR: https://github.com/vegaprotocol/frontend-monorepo/pull/1104/files
thread for issue: https://vegaprotocol.slack.com/archives/C8WS7M50E/p1661245219957939
