### ISSUE TITLE
update vegacapsule readme

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/vegacapsule#261]
There are few things that I missed in Readme when working with vegacapsule. 

- change `go install` to `go install ./...`
- change `vegacapsule network stop` to `vegacapsule network stop --nodes-only` in https://github.com/vegaprotocol/vegacapsule#restoring-on-existing-network
- I'm not sure if this is applicable https://github.com/vegaprotocol/vegacapsule#bootstrapping-a-new-network - as far as I learned, checkpoint need to be loaded into the same network that it was crated from
- some commands and instructions like to read the logs, e.g. `vegacapsule logs` or accessing logs through nomad ui
- (added by @candida-d): `go install ./...` did not install data-node and vegawallet (as claimed in https://github.com/vegaprotocol/vegacapsule/blob/main/install_vega_bins.md#install-manually---build-from-source-more-flexible), that needed to be done manually
- (added by @candida-d):  make it explicit in the readme that you need a registered ssh-key (or remove the requirement?)

Nice to have:
https://github.com/vegaprotocol/vegacapsule#configuration :)

**Comment by karlem** [comment]
Thanks @radoslaw-szpiech for constructive feedback on you experience. I think these are very good points.
