### ISSUE TITLE
Add option to specify metadata in the config.hcl

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#277]
# Description 

Currently We have a config.hcl file but all of the applications config files are separated. It's getting harder and harder to manage secrets for those configs.

I think it would be a good idea to allow specify some metadata in the `config.hcl` and pass all of the values into the application configs templates.

# Motivation

Why we need it? 

For example we need to pass the same values(postgresql db credentials) to the following cofigs:

- explorer
- data-node
- tendermint config
- node-set config (postgresql container config)

# Idea

The metadata section would look like this for example:

```hcl
# config.hcl

metadata {
    pg_host = "127.0.0.1"
    pg_user = "root"
    pg_pass = "example"
    db_name = "vega"
}
```

Then we could inject it as the for the template context, and We can use it like below:

```tmpl
  [Store.Postgres]
    Host = "{{ meta.pg_host }}"
    Port = 5432
    Username = "{{ meta.pg_user }}"
    Password = "{{ meta.pg_pass }}"
    Database = "{{ meta.db_namae }}"
    ApplicationName = "vega block explorer"
```

**Comment by gordsport** [comment]
@daniel1302 - is this requirement still valid?

**Comment by fkondej** [comment]
no longer valid
