### ISSUE TITLE
Vegacapsule block explorer: Number of issues blocking automation

### ISSUE THREAD

**Issue by AndyWhiteVega** [vegaprotocol/vegacapsule#286]
Using block explorer within vegacapsule we keep running into issues when accessing the following pages in the UI:

[Blocks > Select Block with transactions] : 
Bad Gateway 502: “Get \“http://localhost:26617///genesis\“: dial tcp 127.0.0.1:26617: connect: connection refused”.

[Transactions Page] : 
Error on screen upon page load: Cannot fetch transaction: TypeError: Failed to construct ‘URL’: Invalid URL

[Oracles Page] : 
Does not load anything - no network calls made

[Markets Page] : 
Does not load anything - no network calls made

[Governance Proposals Page] : 
Does not load anything - no network calls made

All of the above are working on testnet but not within vegacapsule.

All of the being undertaken in current sprint cannot be automated against until these issues are resolved.
The transactions stuff would be the most beneficial section to unblock first for QA

**Comment by AndyWhiteVega** [comment]
Currently preventing QA from automating against [Done] and [In Progress] items:
https://github.com/vegaprotocol/frontend-monorepo/issues/397
https://github.com/vegaprotocol/frontend-monorepo/issues/1627
https://github.com/vegaprotocol/frontend-monorepo/issues/1682

**Comment by gordsport** [comment]
Closing this issue until:
- https://github.com/vegaprotocol/vegacapsule/issues/280

is implemented and tested.
