### ISSUE TITLE
Vegacapsule HCL templating is not working as expected for second round

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#299]
# Description of templating

Currently, the workflow of the config templating looks like the below:

```mermaid
graph TD;
    1[Load config file from the file system]-->2[Apply HCL parsing for a file system];
    2-->3[Load and put in the config structure all network component templates]
    3-->4[Template network config]
    4-->5[Initialize nodesets]
    5-->6[Template network second time]
```

#  Description of the issue

The issue is that if we template config a second time, it does not contain any template because it has already been templated the first time.

We could use a raw template, but we already have some config values appended in the steps described on the graph.

## Possible solutions:

1. Repeat the parsing process from the beginning second time when we have more data(`generated services`)
2. Parse full config with additional data, do not repeat all previous steps and merge some of the keys into old config with additional data.

## Some informatinons

- We are setting config.HCLBody here: https://github.com/vegaprotocol/vegacapsule/blob/main/config/config.go#L558 - but it is not a template at this point anymore. It has been parsed already and it is parsed file.
- First templating function is called here: https://github.com/vegaprotocol/vegacapsule/blob/main/config/parser.go#L147
- Second templating function is called here: https://github.com/vegaprotocol/vegacapsule/blob/main/config/parser.go#L119

**Comment by karlem** [comment]
After pairing with Daniel we found out that there is no issue like that in Capsule.
