### ISSUE TITLE
vegacapsule does not find vega binary unless vega is in the PATH

### ISSUE THREAD

**Issue by claudiumilea** [vegaprotocol/vegacapsule#305]
unless I do: export PATH=$PATH:/Users/claudiumilea/vega/repos/networkdata

vegacapsule does not find the vega binary

claudiumilea@Claudius-MacBook-Pro networkdata % ./vegacapsule network bootstrap --config-path /Users/claudiumilea/vega/repos/system-tests/vegacapsule/capsule_config.hcl --home-path /Users/claudiumilea/vega/repos/networkdata
Error: failed to parse config file: failed to validate config: failed to set absolute paths: failed to get absolute path for "vega": failed to look up path for "vega": exec: "vega": executable file not found in $PATH
Usage:
  ./vegacapsule network bootstrap [flags]

Flags:
      --config-path string           Path to the config file to generate network from
      --do-not-stop-on-failure       Do not stop partially running network when failed to start
      --force                        Force creating even if folders exists
  -h, --help                         help for bootstrap
      --install                      Automatically installs latest version of vega, data-node and wallet binaries.
      --install-release-tag string   Installs specific release tag version of vega, data-node and wallet binaries.

Global Flags:
      --home-path string   Specify the location of network home directory (default "/Users/claudiumilea/.vegacapsule/testnet")

**Comment by karlem** [comment]
This is not a bug but rather expected behaviour. You have to change the binary path in the `capsule_config.hcl` if you want to behave differently.
