### ISSUE TITLE
Error when executing datanode commands

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vegacapsule#309]
Receive the below error when executing the datanode decentralised history commands.

Looks like the config files are in a separate directory rather than in the node's home directory.

```
Muthus-MBP:networkdata muthupandianvadivelu$ ./vega datanode dehistory show --home /Users/muthupandianvadivelu/muthu/vega/repos/networkdata/testnet/vega/node2
failed to read config:couldn't read file: couldn't read file: open /Users/muthupandianvadivelu/muthu/vega/repos/networkdata/testnet/vega/node2/config/data-node//config.toml: no such file or directory
```

The config files for the data node should be available in the below directory:

`/Users/muthupandianvadivelu/muthu/vega/repos/networkdata/testnet/vega/node2/config/data-node`

Currently they are in this folder:

`/Users/muthupandianvadivelu/muthu/vega/repos/networkdata/testnet/data/node2/config/data-node`

**Comment by gordsport** [comment]
@ettec - please can you review this issue before we schedule?

**Comment by ettec** [comment]
I think is dead @MuthuVega you agree?

**Comment by ettec** [comment]
@MuthuVega confirms dead
