### ISSUE TITLE
Change chain ID of networks generated by vegacapsule

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vegacapsule#319]
Currently networks generated by vegacapsule have the chain ID testnet

This means there will possibly be lots of 'testnet' datanodes around and this will interfere with the decentralised datanode history  testing, so need to update the chain used to ensure it is unique each time and so it should be changed so it is always guarantee unique for that run / network.

**Comment by MuthuVega** [comment]
@gordsport - this issue will need to be prioritised. Thx.

**Comment by ettec** [comment]
Closing - if its still an issue after isolating networks we can use the swarm key override as a better alternative

**Comment by ettec** [comment]
Closing - if its still an issue after isolating networks we can use the swarm key override as a better alternative

**Comment by ettec** [comment]
we want to avoid cross network talk during sys tests, reopening this.
