### ISSUE TITLE
Connect to local ipfs network

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#321]
Currently, the data node is an actual ipfs node. It needs to connect to the ipfs network.

##  Unique chain ID solution 

The one solution is to pass random(unique) chain id for that. If the chain id is the same, the data node has some trash from the previous run. And this is not a real solution because:

1. we cannot start the vega network as a separate thing. 
2. we need to provide a unique chain id. If someone provides the same chain id simultaneously, it can create conflicts.

The above thing makes the solution unacceptable.

## The separate ipfs network

The long-term solution is to start the ipfs binary as part of the vegacapsule network. And point the data node to that ipfs network

**Comment by gordsport** [comment]
This has been mostly addressed in:
- https://github.com/vegaprotocol/vegacapsule/pull/330

However there is some work remaining to not hard code which is the 'golden' / main data node
