### ISSUE TITLE
Tag the release version of vegacapsule

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/vegacapsule#324]
Frontend team would need to have vegacapsule versions tagged in order to add it to github-runner docker image to improve build timings. It would be perfect if it's synchronised with each vega core release. Thanks!

**Comment by gordsport** [comment]
Hey @radoslaw-szpiech 

I have now got an explicit list item for tagging this for the next release in the release ticket:

- https://github.com/vegaprotocol/vega/issues/6839

We will bake this into our process around releases
