### ISSUE TITLE
Unable to start network with more than 9 nodes

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vegacapsule#354]
Unable to start a new node after 9 nodes have been generated / started.

Think this is due to the fact that after 9 , the port numbers of the nodes created are incorrect and hence unable to start the node.

Below is an error message from a Jenkins run when starting a 10th node.

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/31480/artifact/testnet/logs/testnet-nodeset-full-10-full/vega-full-10.stderr-2022-11-30T16%3A14%3A30Z.log/*view*/

This implies that the port number that was assigned to the tendermint for the 10th node to be `266106` , whereas the correct port number would be `26706`

**Comment by daniel1302** [comment]
We are going to redesign port allocation, but to avoid breaking changes in ports we i will use the following rules:
![image](https://user-images.githubusercontent.com/1239637/205081277-e1efb00c-039b-4b14-b186-3ad5a56bc5c8.png)

**Comment by daniel1302** [comment]
Here is a table illustrating how ports are computed: 
![image](https://user-images.githubusercontent.com/1239637/205164477-e84c73bd-d8f5-4ebb-858a-c0c7f45bc754.png)
