### ISSUE TITLE
Improve the `vegacapsule nomad start` command 

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#36]
The `vegacapsule nomad start` command installs the nomad and puts it in the `--home-path` directory.

Then people need to use the `nomad` command directly (e.g. for to collect logs) But now people need to add the `vega capsule home` path into the `$PATH` variable, but it's not obvious.

We need to improve it somehow:

- Print explicitly what they need to do (`export PATH=....`)
- Try to copy nomad binary into one of the `$PATH` directories. 

The goal is to allow people to use the `nomad` client after the `vegacapsule nomad start`

**Comment by gordsport** [comment]
This has been completed
