### ISSUE TITLE
Investigate capsule failure in front end test pipeline

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/vegacapsule#362]
Currently in the FE test pipeline, there seems to be an unknown issue with capsule which is causing the token site to stop working.
The tests run on hosted runners set up by Ops and as far as we know the machines are sufficient in running e2e tests using capsule. 

Full log files during run:
[token-capsule-logs.txt](https://github.com/vegaprotocol/vegacapsule/files/10279370/token-capsule-logs.txt)

Any further information feel free to message @jtsang586 

Issue mentioned in slack thread: https://vegaprotocol.slack.com/archives/C03GXJT3JLT/p1671637772264679

**Comment by fkondej** [comment]
old, not updated.
