### ISSUE TITLE
Add template to allow wallet configuration changes (config.toml)

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vegacapsule#416]
We do need a way to adjust the wallet config when starting VC networks, currently no easy way to do it without running CLI edits and restarting. MaximumRequestDuration is one param we need to increase to avoid Deadline Exceeded errors (give core more time to respond to batch requests).

<workspace>/networkdata/testnet/wallet/config.toml - this is the config VC allow to template

**Comment by gordsport** [comment]
@vega-paul - do you have what you need on this now?
