### ISSUE TITLE
Figure out docker auth for windows

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#66]
# Setup to reproduction

- Windows 10
- WSL
- Docker Desktop

Currently, nomad is using configuration from ~/.docker/config.json but this file has no token for repository even after `docker login`. 

We did a workaround for that adding token manually. We generated token manually with `echo -n "gh_username:gh_personal_token" | base64` and it worked, but this is workaround. We should figure out proper solution as this is blocking people for using the vegacapsule.

**Comment by gordsport** [comment]
Closing as solved as per above
