### ISSUE TITLE
epic: prepare vegacapsule for network release

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#71]
# High-level diagram

![Untitled Diagram](https://user-images.githubusercontent.com/1239637/163371778-681ac4c1-87d5-4638-96ff-865ea04eafba.png)

# Actors

### Vegacapsule server

- Generates new network configuration (only once) when a new network is created for the first time
- Keeps all the networks states locally
   - Generated configurations
   - Generated genesis
   - Generated wallets
   - Generated keys
- Manages network: 
   - Regenerates configuration (for example genesis, when `network_config.hcl` is updated
   - Deploys new binaries
   - Start & stop networks
   - Add/Remove nodes to the network
   - ... more actions to the network

### GIT server

- Keeps all the configuration for networks (no sensitive data). Just `config.hcl` files.
- (Maybe) keeps `genesis.json` and `config.toml` for all the network parts(vega, wallet, tm, etc) - Just for visibility what is the current entire network configuration

### Jenkins server (may be something else)

- Has all pipelines
- Triggers actions on the `vegacapsule server`

### Networks

- Nomad servers

### Developer

- Commits changes to `GIT repository` to pick up next time when the network release is triggered
- Triggers some manual actions on Jenkins server(e.g: network release)

# Questions

- Do we want to manage all of the networks from the single `vegacapsule server`?
- How are We going to provide `vegacapsule compatibility`? - Locally we can just destroy the network and recreate it. It's not a big deal. This is not possible on the long live network.
- Why do not we want to import validator private keys and other sensitive data to the capsule? Currently, We have to keep all files generated to the capsule on the server, and We cannot lose it.
- How do we want to cover changes for information about validators (avatar/URL and other less important info)?

# Related stories

The order is suggested order of implementation

- https://github.com/vegaprotocol/vegacapsule/issues/73
- https://github.com/vegaprotocol/vegacapsule/issues/75
- https://github.com/vegaprotocol/vegacapsule/issues/76
- https://github.com/vegaprotocol/vegacapsule/issues/72
- https://github.com/vegaprotocol/vegacapsule/issues/77
- https://github.com/vegaprotocol/vegacapsule/issues/74
- https://github.com/vegaprotocol/vegacapsule/issues/78
- https://github.com/vegaprotocol/vegacapsule/issues/79

**Comment by gordsport** [comment]
Closing as in `Done` column
