### ISSUE TITLE
implement pipeline for vegacapsule to manage stagnet 3

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#74]
Things to do:

Implement new Jenkins pipelines to:

- [ ] Deploy a new config and binaries to the network. This MUST use vegacapsule.
- [ ] Any other if required? 

See here for more details and dependencies for this story: https://github.com/vegaprotocol/vegacapsule/issues/71

**Comment by gordsport** [comment]
closing as in `done`
